/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login_forgot;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.glasspanepopup.GlassPanePopup;
import com.samplemessage.Message2;

/**
 *
 * @author aruna
 */
public class login extends javax.swing.JFrame {
   JDBC.Jdbc DB = new JDBC.Jdbc();
   Message2 msg = new Message2();
   com.passwordprotect.PasswordEncryption decryPWD = new com.passwordprotect.PasswordEncryption();
    /**
     * Creates new form NewJFrame
     */
    public login() {
        initComponents();
        init();
        GlassPanePopup.install(this);
    }
    public static String memberName;
    public static String usernameSend(){
        String name = "name";
        //return name;
        return memberName;
    }
    
    public void init(){
        header.initMoving(this);
        header.initEvent(this, panelBackground1);
    }
    
    public void login(){
        String userName = userNameTXT.getText();
        String password = passwordTXT.getText();

        if (userName.isEmpty()||password.isEmpty()){
            System.out.println("Fields Can't be Empty");
            errorLBL.setForeground(Color.RED);
            errorLBL.setText("Text Fields Empty");
        }else{
        try {
            java.sql.ResultSet rs = DB.getdata("SELECT * FROM users");
            while(rs.next()){
                String DB_userName = String.valueOf(rs.getString("userName"));
                String DB_password = String.valueOf(rs.getString("password"));
                String status = String.valueOf(rs.getString("status"));
                String DBpassword = decryPWD.decryptPassword(DB_password);

                if(DB_userName.equals(userName) && DBpassword.equals(password)&& status.equals("active")){
                    System.out.println("Done");
                    memberName = userName;
                    errorLBL.setForeground(Color.GREEN);
                    errorLBL.setText("Done");
                    msg.textSet("Login Success "+userNameTXT.getText(), "Loged!");
                    GlassPanePopup.showPopup(msg);
                    com.main.Main dashBoard = new com.main.Main();
                    this.dispose();
                    dashBoard.setVisible(true);
                    
                    break;
                }else{
                    System.out.println("Not Done");
                    errorLBL.setForeground(Color.RED);
                    errorLBL.setText("User Not Found");
                    msg.textSet("User Not Found : "+userNameTXT.getText(), "error!");
                    GlassPanePopup.showPopup(msg);
                }

            }

        } catch (Exception ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }
    
    /*void insertData () {
        try {
            DB.putdata("INSERT INTO users (firstName, lastName, userName, password,role) VALUES ('Vishwa','Dasun','vishwa','1234','admin')");
        } catch (Exception e) {
            System.out.println(e);
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordTXT = new javax.swing.JPasswordField();
        userNameTXT = new javax.swing.JTextField();
        loginBTN = new Components.ButtonGradient();
        errorLBL = new javax.swing.JLabel();
        forgotPasswordLBL = new javax.swing.JLabel();
        header = new com.component.Header();
        jLabel1 = new javax.swing.JLabel();
        panelBackground1 = new com.swing.PanelBackground();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FITNESS GYM LOGIN");
        setName("Login"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordTXT.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        passwordTXT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 153)));
        passwordTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTXTKeyPressed(evt);
            }
        });
        getContentPane().add(passwordTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 339, 200, 30));

        userNameTXT.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        userNameTXT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 153)));
        userNameTXT.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        userNameTXT.setSelectionColor(new java.awt.Color(153, 153, 255));
        userNameTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameTXTKeyPressed(evt);
            }
        });
        getContentPane().add(userNameTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 302, 200, 30));

        loginBTN.setColor1(new java.awt.Color(102, 102, 255));
        loginBTN.setColor2(new java.awt.Color(102, 0, 255));
        loginBTN.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        loginBTN.setLabel("LOGIN");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });
        loginBTN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginBTNKeyPressed(evt);
            }
        });
        getContentPane().add(loginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 140, 40));

        errorLBL.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        errorLBL.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errorLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 200, 30));

        forgotPasswordLBL.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        forgotPasswordLBL.setForeground(new java.awt.Color(0, 0, 255));
        forgotPasswordLBL.setText("Forgot Password");
        forgotPasswordLBL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPasswordLBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        forgotPasswordLBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPasswordLBLMouseClicked(evt);
            }
        });
        getContentPane().add(forgotPasswordLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 450, 120, 20));
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login Cover.png"))); // NOI18N
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(panelBackground1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        
        login();
    }//GEN-LAST:event_loginBTNActionPerformed

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed
        
    }//GEN-LAST:event_jLabel1KeyPressed

    private void loginBTNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginBTNKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    // Enter key pressed
                    System.out.println("Enter key pressed");
                    login();
                    // Perform your desired action here
                }
    }//GEN-LAST:event_loginBTNKeyPressed

    private void passwordTXTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTXTKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    // Enter key pressed
                    System.out.println("Enter key pressed");
                    login();
                    // Perform your desired action here
                }
    }//GEN-LAST:event_passwordTXTKeyPressed

    private void userNameTXTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTXTKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    // Enter key pressed
                    System.out.println("Enter key pressed");
                    login();
                    // Perform your desired action here
                }
    }//GEN-LAST:event_userNameTXTKeyPressed

    private void forgotPasswordLBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPasswordLBLMouseClicked
        forgotPWD pwd = new forgotPWD();
        this.setVisible(false);
        pwd.setVisible(true);
    }//GEN-LAST:event_forgotPasswordLBLMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLBL;
    private javax.swing.JLabel forgotPasswordLBL;
    private com.component.Header header;
    private javax.swing.JLabel jLabel1;
    private Components.ButtonGradient loginBTN;
    private com.swing.PanelBackground panelBackground1;
    private javax.swing.JPasswordField passwordTXT;
    private javax.swing.JTextField userNameTXT;
    // End of variables declaration//GEN-END:variables
}
